# Generated by Django 4.0.3 on 2022-03-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear')], default='s', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='S', max_length=1),
            preserve_default=False,
        ),
    ]
