# Generated by Django 4.0.3 on 2022-05-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estores', '0010_alter_billingaddress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='same_billing_address',
            field=models.BooleanField(default=False),
        ),
    ]
