# Generated by Django 4.0.3 on 2022-05-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estores', '0011_billingaddress_same_billing_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='same_billing_address',
        ),
    ]
